"""Write web/src/template.ts: the scenario template the browser builder fills in (2026-09-27).

The template is trace_track.base_scenario's output: every profile section (the tracer bot, its dodge profile, the LG
beam, the player) and the base map (materials tinted, the frame look's blocks removed), plus the block and spawn
point it copies. Rerun after changing trace_track.py's scenario settings:

    python web/make_template.py
"""
import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import egypt  # noqa: E402
import trace_track as T  # noqa: E402

path, head, m, vols, template, r_w, ride = T.base_scenario(
    "Trace Template", "", 60.0, "test_out/template", tags="Tracking, Smooth",
    top=dict(AimTypeTag="Tracking", AimSubTypeTag="Smoothness"),      # as World Map (the user's own tags)
    drop=["Weapon Profile|BB Gun", "Dodge Profile|Mimic"])            # unused; the game's editor drops them
nl = "\r\n" if "\r\n" in head else "\n"
out = {
    "head": head.replace("\r\n", "\n"),
    "map": m,
    "spawn": vols[0],
    "brush": template,
    "consts": {"SCALE": T.SCALE, "EYE_X": T.EYE_X, "X_BOT": T.X_BOT, "FACE_X": T.FACE_X, "D_BOT": T.D_BOT,
               "D_WALL": T.D_WALL, "PROC_UNIT": egypt.PROC_UNIT, "UV_UNIT": egypt.UV_UNIT,
               "BRUSH_NAME": egypt.BRUSH_NAME, "GROUP_BASE": egypt.GROUP_BASE,
               "MAP_SCALE": float(next(l.split("=", 1)[1] for l in head.splitlines() if l.startswith("MapScale=")))},
}
ts = ("// Generated by web/make_template.py from trace_track.base_scenario (do not edit by hand).\n"
      "export const TEMPLATE = " + json.dumps(out, indent=1) + " as const;\n")
dest = Path(__file__).resolve().parent / "src" / "template.ts"
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text(ts, encoding="utf-8")
print(f"{dest}: {len(ts) / 1000:.0f} kB")
